def all_pods
    pod 'Alamofire', '~> 4.7.2'
    pod 'R.swift', '~> 5.1.0'
end

target 'TestiOS2' do
    platform :ios, '10.3'
    all_pods
end

target 'TestiOS2Tests' do
    platform :ios, '10.3'
    all_pods
    pod 'Quick', '2.2.0'
    pod 'Nimble', '8.0.4'
end